apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /   # This would strip /api etc out of the request
spec:
  rules:
    - http:
        paths:
          - path: / # Matches requests directly to the ip to port 3000
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 5000 # Client is exposing port 3000
          - path: /api/
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 8080 # Server port
          - path: /swagger-ui.html
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 8080 # Server port

# I'm not sure that the /swagger-ui.html path achieves anything
# Would be nice to figure out how to access the Swagger page
